# Generated by Django 3.2.6 on 2021-08-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieReco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.BooleanField()),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieReco.movie')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieenthousiast',
            name='appreciation',
        ),
        migrations.DeleteModel(
            name='Appreciation',
        ),
        migrations.DeleteModel(
            name='MovieEnthousiast',
        ),
    ]
