# Generated by Django 3.2.6 on 2021-08-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReco', '0002_auto_20210817_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
