# Generated by Django 3.2.6 on 2021-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReco', '0003_alter_usermovierate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSynopsisDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=7, max_digits=8, null=True)),
                ('pairing_movies', models.ManyToManyField(blank=True, to='MovieReco.Movie')),
            ],
        ),
    ]
