# Generated by Django 3.2.6 on 2021-08-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReco', '0004_moviesynopsisdistance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesynopsisdistance',
            old_name='distance',
            new_name='distance_score',
        ),
    ]
