# Generated by Django 3.2.6 on 2021-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReco', '0007_movie_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieContentSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.IntegerField(null=True)),
                ('pairing_movies', models.ManyToManyField(blank=True, to='MovieReco.Movie')),
            ],
        ),
    ]
